version: '3.8'

services:
  # ML API Service
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Streamlit Web Interface
  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - API_URL=http://api:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # MLflow Tracking Server
  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow.Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./models:/app/models
    environment:
      - MLFLOW_BACKEND_STORE_URI=file:///app/mlruns
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/mlruns
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  mlruns_data:
  models_data:

networks:
  default:
    name: ml-house-prediction-network
    driver: bridge